document: modularity-testing
version: 1
name: s2i-python-container
testdependecies:
    rpms:
        - curl
        - source-to-image
default_module: docker
module:
    docker:
        setup: IMAGE=centos/python-27-centos7;
            APP_CONTAINER=s2i-python-sample;
            s2i build https://github.com/sclorg/s2i-python-container.git --context-dir=2.7/test/setup-test-app/ $IMAGE $APP_CONTAINER
        start: docker run -p 8080:8080
        container: docker=s2i-python-sample
